spring:
  datasource:
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:test
    username: sa
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql

# mybatis配置
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: cn.chenzw.springboot.mybatis.modules.ext.log.MybatisSqlPrintStatementOutImpl
