version: "3"

services:
  gateway:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - 8770:8770
    environment:
      - NACOS_HOST=nacos
    networks:
      - my_network

networks:
  my_network:
    external: true


